export enum CheckoutSessionEndReason {
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  ABANDONED = 'ABANDONED',
  EXPIRED = 'EXPIRED',
}

export enum CheckoutEventType {
  CHECKOUT_SESSION_STARTED = 'CHECKOUT_SESSION_STARTED',
  CHECKOUT_QA_STARTED = 'CHECKOUT_QA_STARTED',
  CHECKOUT_STARTED = 'CHECKOUT_STARTED',
  CUSTOMER_DATA_SUBMITTED = 'CUSTOMER_DATA_SUBMITTED',
  PAYMENT_METHOD_SELECTED = 'PAYMENT_METHOD_SELECTED',
  WALLET_CONNECTED = 'WALLET_CONNECTED',
  CRYPTO_ASSET_SELECTED = 'CRYPTO_ASSET_SELECTED',
  PAYMENT_CONFIRM_CLICKED = 'PAYMENT_CONFIRM_CLICKED',
  PAYMENT_INTENT_CREATED = 'PAYMENT_INTENT_CREATED',
  PIX_PRESENTED = 'PIX_PRESENTED',
  CARD_FORM_PRESENTED = 'CARD_FORM_PRESENTED',
  CARD_PAYMENT_CONFIRMED = 'CARD_PAYMENT_CONFIRMED',
  CRYPTO_ESCROW_CREATED = 'CRYPTO_ESCROW_CREATED',
  CRYPTO_TX_SIGNED = 'CRYPTO_TX_SIGNED',
  CRYPTO_TX_SUBMITTED = 'CRYPTO_TX_SUBMITTED',
  CRYPTO_TX_CONFIRMED = 'CRYPTO_TX_CONFIRMED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_SUCCEEDED = 'PAYMENT_SUCCEEDED',
  CHECKOUT_ABANDONED = 'CHECKOUT_ABANDONED',
}

export enum CheckoutEventStep {
  WELCOME = 'WELCOME',
  QA = 'QA',
  CHECKOUT_STARTED = 'CHECKOUT_STARTED',
  CUSTOMER_DATA = 'CUSTOMER_DATA',
  PAYMENT_METHOD = 'PAYMENT_METHOD',
  WALLET_CONNECTION = 'WALLET_CONNECTION',
  PAYMENT_REVIEW = 'PAYMENT_REVIEW',
  PAYMENT = 'PAYMENT',
  CONFIRMATION = 'CONFIRMATION',
}

export enum CheckoutEventPaymentMethod {
  PIX = 'PIX',
  CARD = 'CARD',
  CRYPTO = 'CRYPTO',
}

export enum CheckoutEventSource {
  FRONTEND = 'FRONTEND',
  BACKEND = 'BACKEND',
}
